name: Push to main branch
on: [push]
jobs:
  verfiy-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.11'
          cache: 'pipenv'
          cache-dependency-path: '**/Pipfile.lock'

      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: pipenv install -d
      
      - name: Run Tests
        run: pytest
